name: liri-snap-packages
summary: Snap packages for Liri
environment:
  scripts:
    setup: |
      require('python', '3.5.0')
      baka = require('baka', '0.1.0')

      # Prerequisites to make snap work
      baka.box.run('apt-get', 'dist-upgrade', '-y')
      baka.box.run('apt-get', 'install', 'squashfuse', '-y')

      # Install platform snap package
      baka.box.run('snap', 'install', '--edge', 'liri-platform0')
jobs:
  - name: base
    extends: base
    source: base
    source-type: local
  - name: browser-snap
    extends: snapcraft
    source: browser
    source-type: local
    scripts:
      setup: |
        baka = require('baka', '0.1.0')
        baka.box.run('cp', '-r', '../base/snap/plugins', 'snap')
  - name: calculator-snap
    extends: snapcraft
    source: calculator
    source-type: local
    scripts:
      setup: |
        baka = require('baka', '0.1.0')
        baka.box.run('cp', '-r', '../base/snap/plugins', 'snap')
  - name: text-snap
    extends: snapcraft
    source: text
    source-type: local
    scripts:
      setup: |
        baka = require('baka', '0.1.0')
        baka.box.run('cp', '-r', '../base/snap/plugins', 'snap')
  - name: files-snap
    extends: snapcraft
    source: files
    source-type: local
    scripts:
      setup: |
        baka = require('baka', '0.1.0')
        baka.box.run('cp', '-r', '../base/snap/plugins', 'snap')
  - name: shell-snap
    extends: snapcraft
    source: shell
    source-type: local
    scripts:
      setup: |
        baka = require('baka', '0.1.0')
        baka.box.run('cp', '-r', '../base/snap/plugins', 'snap')
